// src/features/common/ui/components/cookie-state/cookie-state.tsx
import Cookie from 'js-cookie'
import { createSignal, onMount, Show } from 'solid-js'

const design = 'adaptable-center-text text-base lg:text-xl font-semibold'

export const CookieState = () => {
  const [data, setData] = createSignal<string | undefined>('')

  onMount(() => setData(Cookie.get('data')))

  return (
    <Show
      fallback={
        <p class={design}>
          Cookie State: Yes, you write <b>{data()}</b>
        </p>
      }
      when={data() === undefined || data() === ''}
    >
      {<p class={design}>Cookie State: Not yet.</p>}
    </Show>
  )
}

// src/lib/components/cookie-state/CookieState.svelte
<script lang='ts'>
  import Cookie from 'js-cookie';

  const data = Cookie.get('data');
  const design =
    'adaptable-center-text text-base lg:text-xl font-semibold';
</script>

{#if data}
  <p class={design}>Cookie State: Yes, you write <b>{ data }</b></p>
{:else}
  <p class={design}>Cookie State: Not yet.</p>
{/if}
