// src/lib/common/components/cookie-state.tsx
/* eslint-disable no-undefined */
import { component$, useSignal, useVisibleTask$ } from '@builder.io/qwik';
import Cookie from 'js-cookie';

const design = 'adaptable-center-text text-base lg:text-xl font-semibold';

export const CookieState = component$(() => {
  const data = useSignal<string | undefined>('');

  useVisibleTask$(() => {
    data.value = Cookie.get('data');
  });

  return (
    <p class={design}>
      Cookie State:
      {data.value !== undefined ? (
        <>
          Yes, you write <b>{data}</b>
        </>
      ) : (
        <>Not yet.</>
      )}
    </p>
  );
});

// src/lib/components/cookie-state/CookieState.svelte
<script lang='ts'>
  import Cookie from 'js-cookie';

  const data = Cookie.get('data');
  const design =
    'adaptable-center-text text-base lg:text-xl font-semibold';
</script>

{#if data}
  <p class={design}>Cookie State: Yes, you write <b>{ data }</b></p>
{:else}
  <p class={design}>Cookie State: Not yet.</p>
{/if}
