// src/lib/home/components/call.tsx
import { component$, Resource, useResource$, Slot } from '@builder.io/qwik'

import { getBitcoin } from '@/home/services'
import type { Binance } from '../models'

export const Call = component$(() => {
  const btcResource = useResource$<Binance>(getBitcoin)

  return (
    <Resource
      value={btcResource}
      onPending={() => <Slot />}
      onResolved={bin => (
        <>
          <p class='adaptable-call'>
            Symbol:
            {bin.symbol}
          </p>
          <p class='adaptable-call'>
            Price:
            {bin.askPrice}
          </p>
        </>
      )}
    />
  )
})

// src/lib/home/components/Call.svelte
<script lang='ts'>
  import { getBitcoin } from '@/home/services';

  const textStyle =
    'adaptable-center-text text-base lg:text-lg font-semibold';

  const btc = getBitcoin();
</script>

{#await btc}
  <slot />
{:then bin}
  <p class={textStyle}>Symbol: {bin.symbol}</p>
  <p class={textStyle}>Price: {bin.askPrice}</p>
{/await}
