// src/features/common/ui/components/storage-state/storage-state.tsx
import { useStore } from '@nanostores/solid'
import { Show } from 'solid-js'

import { inject } from '~/di'

export const StorageState = () => {
  const dataService = inject.resolve('dataService')

  const data = useStore(dataService.dataStore)

  return (
    <p class='adaptable-center-text text-base font-semibold lg:text-xl'>
      Store State:&nbsp;
      <Show
        fallback={
          <>
            Yes, you write <b>{data()}</b>
          </>
        }
        when={data() === undefined}
      >
        <> Not yet.</>
      </Show>
    </p>
  )
}

// src/lib/common/components/storage-state/storage-state.tsx
import {
  component$,
  $,
  useSignal,
  useOnDocument,
  useVisibleTask$
} from '@builder.io/qwik'

import { data } from '@/common/stores/data-store'

export const StorageState = component$(() => {
  const dataSignal = useSignal<string | undefined>()

  useVisibleTask$(() => {
    dataSignal.value = data.get()
  })

  useOnDocument(
    'data',
    $((event: CustomEvent<string>) => {
      dataSignal.value = event.detail
    })
  )

  return (
    <p class='adaptable-center-text text-base font-semibold lg:text-xl'>
      Store State:
      {dataSignal.value != null ? (
        <>
          Yes, you write <b>{dataSignal.value}</b>
        </>
      ) : (
        <>Not yet.</>
      )}
    </p>
  )
})
