// src/features/common/ui/components/toggler/toggler.tsx
import './toggler.css'

import { useStore } from '@nanostores/solid'
import { createSignal, onMount } from 'solid-js'

import { inject } from '~/config'

export const Toggler = () => {
  const { themeStore, toggle } = inject.resolve('themeService')

  const theme = useStore(themeStore)

  const [dark, setDark] = createSignal(false)

  onMount(() => setDark(theme().isDark))

  return (
    <div class='relative'>
      <label
        class='mb-4 inline-flex cursor-pointer items-center'
        for='checked-toggle'
      >
        <input
          checked={dark()}
          class='peer sr-only'
          id='checked-toggle'
          onChange={_ => toggle()}
          type='checkbox'
          value=''
        />
        <div class={`${theme().togglePeer} toggle-design peer`} />
        <span class='adaptable-text ml-3 select-none text-sm font-medium'>
          Dark Mode
        </span>
      </label>
    </div>
  )
}

// src/lib/components/toggler/Toggler.svelte
<script lang='ts'>
  import { theme, toggle } from '@/stores/theme-store';

  import './Toggler.css';
</script>

<div class='relative'>
  <div class='flex items-center justify-center w-full'>
    <label
      for='checked-toggle'
      class='inline-flex items-center mb-4 cursor-pointer'
    >
      <input
        type='checkbox'
        value=''
        id='checked-toggle'
        class='sr-only peer'
        checked={$theme.isDark}
        on:change={toggle}
      />
      <div class={`${$theme.togglePeer} peer toggle-design`}></div>
      <span class='ml-3 text-sm font-medium adaptable-text select-none'>
        Dark Mode
      </span>
    </label>
  </div>
</div>
